
/* Функция, импортирующая из GS данные с отчет по adContent */

let
    Source = (url_Google_adContent as text) => let
    Source = Csv.Document(Web.Contents(url_Google_adContent),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"ExpandedFinalUrlString", type text}, {"Impressions", Int64.Type}, {"Clicks", Int64.Type}, {"Cost", type text}, {"Conversions", type text}}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "ExpandedFinalUrlString", Splitter.SplitTextByDelimiter("utm_content=", QuoteStyle.Csv), {"ExpandedFinalUrlString.1", "ExpandedFinalUrlString.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"ExpandedFinalUrlString.1", type text}, {"ExpandedFinalUrlString.2", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"ExpandedFinalUrlString.2", "utm_content"}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns", "utm_content", "utm_content - Copy"),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Duplicated Column", "utm_content - Copy", Splitter.SplitTextByDelimiter("|", QuoteStyle.Csv), {"utm_content - Copy.1", "utm_content - Copy.2", "utm_content - Copy.3", "utm_content - Copy.4", "utm_content - Copy.5", "utm_content - Copy.6", "utm_content - Copy.7", "utm_content - Copy.8", "utm_content - Copy.9", "utm_content - Copy.10", "utm_content - Copy.11", "utm_content - Copy.12", "utm_content - Copy.13", "utm_content - Copy.14", "utm_content - Copy.15", "utm_content - Copy.16", "utm_content - Copy.17", "utm_content - Copy.18", "utm_content - Copy.19", "utm_content - Copy.20", "utm_content - Copy.21", "utm_content - Copy.22"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"utm_content - Copy.1", type text}, {"utm_content - Copy.2", type text}, {"utm_content - Copy.3", type text}, {"utm_content - Copy.4", type number}, {"utm_content - Copy.5", type text}, {"utm_content - Copy.6", type number}, {"utm_content - Copy.7", type text}, {"utm_content - Copy.8", type number}, {"utm_content - Copy.9", type text}, {"utm_content - Copy.10", type text}, {"utm_content - Copy.11", type text}, {"utm_content - Copy.12", type text}, {"utm_content - Copy.13", type text}, {"utm_content - Copy.14", type text}, {"utm_content - Copy.15", type text}, {"utm_content - Copy.16", type text}, {"utm_content - Copy.17", type text}, {"utm_content - Copy.18", type text}, {"utm_content - Copy.19", type text}, {"utm_content - Copy.20", Int64.Type}, {"utm_content - Copy.21", type text}, {"utm_content - Copy.22", type text}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type2",{{"utm_content - Copy.22", "landing"}, {"utm_content - Copy.20", "reg"}, {"utm_content - Copy.17", "service"}, {"utm_content - Copy.16", "dvc"}}),
    #"Split Column by Delimiter2" = Table.SplitColumn(#"Renamed Columns1", "utm_content - Copy.14", Splitter.SplitTextByDelimiter("_", QuoteStyle.Csv), {"utm_content - Copy.14.1", "utm_content - Copy.14.2"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Delimiter2",{{"utm_content - Copy.14.1", type text}, {"utm_content - Copy.14.2", type text}}),
    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type3",{{"utm_content - Copy.14.1", "placement_type"}, {"utm_content - Copy.14.2", "placement"}, {"utm_content - Copy.12", "pos"}, {"utm_content - Copy.10", "adp"}}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Renamed Columns2",{{"utm_content - Copy.8", type text}}),
    #"Renamed Columns3" = Table.RenameColumns(#"Changed Type4",{{"utm_content - Copy.8", "aid"}}),
    #"Changed Type5" = Table.TransformColumnTypes(#"Renamed Columns3",{{"utm_content - Copy.6", type text}}),
    #"Renamed Columns4" = Table.RenameColumns(#"Changed Type5",{{"utm_content - Copy.6", "gid"}}),
    #"Changed Type6" = Table.TransformColumnTypes(#"Renamed Columns4",{{"utm_content - Copy.4", type text}}),
    #"Renamed Columns5" = Table.RenameColumns(#"Changed Type6",{{"utm_content - Copy.4", "cid"}}),
    #"Split Column by Delimiter3" = Table.SplitColumn(#"Renamed Columns5", "utm_content - Copy.1", Splitter.SplitTextByDelimiter("kwd-", QuoteStyle.Csv), {"utm_content - Copy.1.1", "utm_content - Copy.1.2"}),
    #"Changed Type7" = Table.TransformColumnTypes(#"Split Column by Delimiter3",{{"utm_content - Copy.1.1", type text}, {"utm_content - Copy.1.2", type text}}),
    #"Renamed Columns6" = Table.RenameColumns(#"Changed Type7",{{"utm_content - Copy.1.2", "kid"}}),
    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns6",{"utm_content - Copy.1.1", "utm_content - Copy.2", "utm_content - Copy.3", "utm_content - Copy.5", "utm_content - Copy.7", "utm_content - Copy.9", "utm_content - Copy.11", "utm_content - Copy.13", "utm_content - Copy.15", "service", "utm_content - Copy.19", "utm_content - Copy.21"})
in
    #"Removed Columns"
in
    Source
