
/* Функция, импортирующая из GS данные с отчет по adContent */

let
    Source = (url_Google_adContent as text) => let
    Source = Csv.Document(Web.Contents(url_Google_adContent),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Promoted Headers", "ExpandedFinalUrlString", Splitter.SplitTextByDelimiter("utm_content=", QuoteStyle.Csv), {"ExpandedFinalUrlString.1", "ExpandedFinalUrlString.2"}),
    #"Renamed Columns" = Table.RenameColumns(#"Split Column by Delimiter",{{"ExpandedFinalUrlString.2", "utm_content"}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns", "utm_content", "utm_content - Copy"),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Duplicated Column", "utm_content - Copy", Splitter.SplitTextByDelimiter("|", QuoteStyle.Csv), {"utm_content - Copy.1", "utm_content - Copy.2", "utm_content - Copy.3", "utm_content - Copy.4", "utm_content - Copy.5", "utm_content - Copy.6", "utm_content - Copy.7", "utm_content - Copy.8", "utm_content - Copy.9", "utm_content - Copy.10", "utm_content - Copy.11", "utm_content - Copy.12", "utm_content - Copy.13", "utm_content - Copy.14", "utm_content - Copy.15", "utm_content - Copy.16", "utm_content - Copy.17", "utm_content - Copy.18", "utm_content - Copy.19", "utm_content - Copy.20", "utm_content - Copy.21", "utm_content - Copy.22", "utm_content - Copy.23", "utm_content - Copy.24"}),
    #"Split Column by Delimiter2" = Table.SplitColumn(#"Split Column by Delimiter1", "utm_content - Copy.14", Splitter.SplitTextByDelimiter("_", QuoteStyle.Csv), {"utm_content - Copy.14.1", "utm_content - Copy.14.2"}),
    #"Split Column by Delimiter3" = Table.SplitColumn(#"Split Column by Delimiter2", "utm_content - Copy.1", Splitter.SplitTextByDelimiter("kwd-", QuoteStyle.Csv), {"utm_content - Copy.1.1", "utm_content - Copy.1.2"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Split Column by Delimiter3",{{"utm_content - Copy.1.2", "kid"}, {"utm_content - Copy.4", "cid"}, {"utm_content - Copy.6", "gid"}, {"utm_content - Copy.8", "aid"}, {"utm_content - Copy.12", "pos"}, {"utm_content - Copy.14.1", "placement_type"}, {"utm_content - Copy.14.2", "placement"}, {"utm_content - Copy.16", "dvc"}, {"utm_content - Copy.18", "service"}, {"utm_content - Copy.20", "reg"}, {"utm_content - Copy.22", "model"}, {"utm_content - Copy.24", "tip"}}),
    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns1",{"utm_content - Copy.1.1", "utm_content - Copy.2", "utm_content - Copy.3", "utm_content - Copy.5", "utm_content - Copy.7", "utm_content - Copy.9", "utm_content - Copy.10", "utm_content - Copy.11", "utm_content - Copy.13", "utm_content - Copy.15", "utm_content - Copy.17", "utm_content - Copy.19", "utm_content - Copy.21", "utm_content - Copy.23"})

in
    #"Removed Columns"
in
    Source
