//Функция возвращает официальный курс доллара на дату, заданную в формате 12/03/2019

let
    Source = (Date as text) => let
        Source = Xml.Tables(Web.Contents(Text.Combine({"http://www.cbr.ru/scripts/XML_daily.asp?date_req=", Date, "&VAL_NM_RQ=R01235"}))),
        #"Removed Columns" = Table.RemoveColumns(Source,{"Attribute:Date", "Attribute:name"}),
        #"Expanded Valute" = Table.ExpandTableColumn(#"Removed Columns", "Valute", {"NumCode", "Value"}, {"Valute.NumCode", "Valute.Value"}),
        #"Filtered Rows" = Table.SelectRows(#"Expanded Valute", each ([Valute.NumCode] = "840")),
        #"Removed Columns1" = Table.RemoveColumns(#"Filtered Rows",{"Valute.NumCode"}),
        #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns1",{{"Valute.Value", type number}})
    in
        #"Changed Type"
in
    Source
